Repository jenkinsci/pipeline-milestone-step-plugin, pull requests merged in 2022-02, with the labels that each got.

#43 Enable CD
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
Labels: chore

#44 Enable cd
  .github/dependabot.yml
  .github/release-drafter.yml
Labels: chore

#27 [JENKINS-43353] Removing `killPrecedingBuild` demo test
  src/test/java/org/jenkinsci/plugins/pipeline/milestone/MilestoneStepTest.java
Labels: chore, internal

#45 Bump to 2.277.3 minimum
  pom.xml
Labels: enhancement
